### ISSUE TITLE
[BUG] load_classification function not working and time-series classification's website down

### ISSUE THREAD

**Issue by fmorenopino** [aeon-toolkit/aeon#1502]
### Describe the bug

Hi, I think that the website https://www.timeseriesclassification.com/index.php has been down for a couple of days now. Further, on python, I cannot use the function load_classification (from aeon.datasets import load_classification) to download non-previously used datasets (for example, X, Y = load_classification("PhonemeSpectra") is not working).

### Steps/Code to reproduce the bug

```
from aeon.datasets import load_classification
X, Y = load_classification("PhonemeSpectra")
```

### Expected results

No error is thrown

### Actual results

```
Traceback (most recent call last):
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/home/fernandom/.local/lib/python3.10/site-packages/aeon/datasets/_data_loaders.py", line 1359, in load_classification
    raise e
  File "/nfs/home/fernandom/.local/lib/python3.10/site-packages/aeon/datasets/_data_loaders.py", line 1354, in load_classification
    response = urlopen(req, timeout=60)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/nfs/home/fernandom/miniconda3/envs/contrastive/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -5] No address associated with hostname>
```

### Versions

System:
    python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
executable: /nfs/home/fernandom/miniconda3/envs/contrastive/bin/python
   machine: Linux-5.15.0-101-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.3.2
   setuptools: 68.0.0
 scikit-learn: 1.3.0
         aeon: 0.8.1
  statsmodels: None
        numpy: 1.24.3
        scipy: 1.11.1
       pandas: 2.0.3
   matplotlib: 3.7.2
       joblib: 1.3.1
        numba: 0.57.1
     pmdarima: None
      tsfresh: None

**Comment by TonyBagnall** [comment]
hi, yes the website is down at the moment, sorry about that. We are switching over accounts for the running of timeseriesclassification.com and it is taking longer than I hoped. Should be up and running by the end of the week.

**Comment by fmorenopino** [comment]
Thanks @TonyBagnall. Is there any alternative I can use to 'load_classification' in python besides manually downloading all the datasets?

**Comment by TonyBagnall** [comment]
not to my knowledge, but there might be other locations. If you download the datasets, load_classification will load from disk if you give it the location, or use load_from_tsfile. I'll post here when its back up, but I need to rebuild all the databases and upload all the files even once they have done the switch and its just me doing tsc.com in my spare time really.

**Comment by TonyBagnall** [comment]
UK2.net not coming out of this well btw!

**Comment by fmorenopino** [comment]
Thanks for the feedback, @TonyBagnall. I will give it a try to load them locally in the meantime. Thanks again.

**Comment by TonyBagnall** [comment]
we can give you the datasets if you need them, just email us

**Comment by MatthewMiddlehurst** [comment]
We should keep this open while the website remains down IMO

**Comment by TonyBagnall** [comment]
we can keep it open, but I dont think it qualifies as an aeon bug

**Comment by fmorenopino** [comment]
Hi, is there any update on this? Thanks again.

**Comment by lmriccardo** [comment]
It seems that the site is till down

**Comment by technocreep** [comment]
If there is urgent need for someone I could share a link to most of the datasets, univariate as well as multivariate, just saying

**Comment by MatthewMiddlehurst** [comment]
We are hoping this should be resolved soon, but as mentioned Tony can provide the datasets if you email him at A.J.Bagnall@soton.ac.uk.

**Comment by TonyBagnall** [comment]
update, our ISP are still being hopeless, so we are backing up the data onto zenodo and will release a patch to use zenodo as backup

**Comment by TonyBagnall** [comment]
@lmriccardo @fmorenopino Everything should now work. FYI we have also uploaded all the data to zenodo and if timeseriesclassification.com is down, load_classifier (and shortly load_regression) go there instead. Any problems, let me know, otherwise I will close this issue

**Comment by TonyBagnall** [comment]
going to close this now, all should work (and be much faster!)
