### ISSUE TITLE
[ENH] Improve `BaseCollectionEstimator` `_check_X` collection datatype validation

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1889]
### Describe the feature or idea you want to propose

`_check_X` had checks for multivariate, unequal length, and missing values, but this could be improved with checks for specific datatypes i.e. `numpy3d`, `np-list` etc. 

We should check if the input is one of these and if it is correctly formatted. Some of this probably done elsewhere, but likely will not raise an infromative error.

### Describe your proposed solution

Create a function i.e. `check_collection` and return a informative errors if the datatype is not valid.

**Comment by Cyril-Meyer** [comment]
Check can be done using [get_type](https://github.com/aeon-toolkit/aeon/blob/c469e872aca68e41e57792adbeaa3e42d5fd05a8/aeon/utils/validation/collection.py#L212).
`_check_X` is calling it through `_get_X_metadata` -> `is_univariate` -> `get_type`.

```python
from aeon.base import BaseCollectionEstimator

dummy = BaseCollectionEstimator()
all_tags = {
    "capability:multivariate": True,
    "capability:unequal_length": True,
    "capability:missing_values": True,
}
dummy.set_tags(**all_tags)

X = 42
dummy._check_X(X)
```


```python
Traceback (most recent call last):
  File "C:\Users\cyril\Documents\Development\aeon\cyril.py", line 12, in <module>
    dummy._check_X(X)
  File "C:\Users\cyril\Documents\Development\aeon\aeon\base\_base_collection.py", line 139, in _check_X
    metadata = self._get_X_metadata(X)
  File "C:\Users\cyril\Documents\Development\aeon\aeon\base\_base_collection.py", line 232, in _get_X_metadata
    metadata["multivariate"] = not is_univariate(X)
  File "C:\Users\cyril\Documents\Development\aeon\aeon\utils\validation\collection.py", line 365, in is_univariate
    type = get_type(X)
  File "C:\Users\cyril\Documents\Development\aeon\aeon\utils\validation\collection.py", line 276, in get_type
    raise TypeError(
TypeError: ERROR passed input of type <class 'int'>, must be of type np.ndarray, pd.DataFrame or list of np.ndarray/pd.DataFrame
```

**Comment by MatthewMiddlehurst** [comment]
I feel this could be improved still, i.e. moved to the top level and link to resources for accepted data types.

There are also some aspects that are still not checked I think, i.e. is the `dtype` of the input valid (int or float)?

**Comment by TonyBagnall** [comment]
just trawling around old issues, my main thought on this is I dont like the name of get_type(X). A function called get_type should return something, and thats how its used elsewhere. Here its just called. Also the raise_error argument smells to me :)

There is also a lot of redundancy here. 

_check_X calls get_type, after which _get_X_metadata calls several utilities such as is_univariate, has_missing, is_equal_length, get_n_cases and get_n_channels.

Those utilities generally determine the collection type again. Conversion then calls get_type again. For list representations, this can mean repeatedly iterating over all cases merely to rediscover that the object is an np-list or df-list.

get_type calls during one _check_X: 9
   _base_collection.py:174 in _check_X        <-- value discarded
   collection.py:136 in get_n_channels
   collection.py:224 in has_missing
   collection.py:183 in is_equal_length
   collection.py:79  in get_n_cases
   collection.py:136 in get_n_channels
   collection.py:105 in get_n_timepoints
   collection.py:183 in is_equal_length
   collection.py:546 in check_collection_variance

I think this issue is a bit stale, and a new issue would look at reducing the redundancy in calls. For np-list, get_type is O(n_cases) since it walks every array checking dtype and ndim, so this isn't free

this is actually a bit of a drag
numpy3D (500,1,500)      _check_X= 1.752 ms   all 9 get_type calls =  2.1%
np-list n=500 len=500    _check_X= 31.118 ms  all 9 get_type calls = 10.7%
np-list n=5000 len=100   _check_X=296.894 ms  all 9 get_type calls = 10.9%

claude says this after raising my concern

Line 174 alone is about 1.2% on np-list. So there's no performance case for touching it, and the redundancy across all nine is a separate design question — the natural fix there is to resolve the type once and thread it through as an optional input_type argument, which the helpers don't currently accept.

Which I think strengthens your point rather than weakening it. The single call site where get_type doesn't read as a getter exists purely to make a traceback shallower — a legitimate goal, but the intent is completely illegible at the call site. check_collection(X) on that line would say exactly what it does and cost nothing, and it's the same check_*-validates-and-raises convention already used by check_collection_variance two hundred lines down the same file. That one-line substitution is separable from the rename and the deprecation cycle.

I think I will close this and create a new issue, reopen if you disagree @MatthewMiddlehurst
