### ISSUE TITLE
[BUG] CI broken on python 3.9?

### ISSUE THREAD

**Issue by patrickzib** [aeon-toolkit/aeon#2462]
### Describe the bug

CI seems to be broken. 

Takes > 30 minutes on windows/python 3.9 and ubuntu/python 3.9 for resolving dependencies:

```
Collecting sparse (from aeon==1.0.0)
  Using cached sparse-0.15.3-py2.py3-none-any.whl.metadata (4.5 kB)
  Using cached sparse-0.15.2-py2.py3-none-any.whl.metadata (4.5 kB)
  Using cached sparse-0.15.1-py2.py3-none-any.whl.metadata (4.5 kB)
  Using cached sparse-0.15.0-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached sparse-0.14.0-py2.py3-none-any.whl.metadata (2.9 kB)
  Using cached sparse-0.13.0-py2.py3-none-any.whl.metadata (2.9 kB)
  Using cached sparse-0.12.0-py2.py3-none-any.whl.metadata (3.0 kB)
  Using cached sparse-0.11.2-py2.py3-none-any.whl.metadata (3.0 kB)
  Using cached sparse-0.11.1-py2.py3-none-any.whl.metadata (3.0 kB)
  Using cached sparse-0.11.0-py2.py3-none-any.whl.metadata (3.0 kB)
  Using cached sparse-0.10.0-py2.py3-none-any.whl.metadata (3.0 kB)
  Using cached sparse-0.9.1-py2.py3-none-any.whl.metadata (2.8 kB)
  Using cached sparse-0.8.0-py2.py3-none-any.whl.metadata (2.8 kB)
  Using cached sparse-0.7.0-py2.py3-none-any.whl.metadata (2.7 kB)
  Using cached sparse-0.6.0-py2.py3-none-any.whl.metadata (2.7 kB)
  Using cached sparse-0.5.0-py2.py3-none-any.whl.metadata (2.7 kB)
  Using cached sparse-0.4.1-py2.py3-none-any.whl.metadata (2.9 kB)
  Using cached sparse-0.4.0-py2.py3-none-any.whl.metadata (2.9 kB)
  Using cached sparse-0.3.1-py2.py3-none-any.whl.metadata (1.3 kB)
  Using cached sparse-0.3.0-py2.py3-none-any.whl.metadata (1.3 kB)
  Using cached sparse-0.2.0-py2.py3-none-any.whl.metadata (5.8 kB)
  Using cached sparse-0.1.1-py2.py3-none-any.whl.metadata (4.6 kB)
  Using cached sparse-0.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
  Using cached sparse-0.0.1-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting imbalanced-learn (from aeon==1.0.0)
  Using cached imbalanced_learn-0.12.3-py3-none-any.whl.metadata (8.3 kB)
  Using cached imbalanced_learn-0.12.2-py3-none-any.whl.metadata (8.2 kB)
  Using cached imbalanced_learn-0.12.1-py3-none-any.whl.metadata (8.2 kB)
  Using cached imbalanced_learn-0.12.0-py3-none-any.whl.metadata (8.2 kB)
  Using cached imbalanced_learn-0.11.0-py3-none-any.whl.metadata (8.3 kB)
  Using cached imbalanced_learn-0.10.1-py3-none-any.whl.metadata (8.2 kB)
  Using cached imbalanced_learn-0.10.0-py3-none-any.whl.metadata (8.2 kB)
  Using cached imbalanced_learn-0.9.1-py3-none-any.whl.metadata (13 kB)
  Using cached imbalanced_learn-0.9.0-py3-none-any.whl.metadata (13 kB)
  Using cached imbalanced_learn-0.8.1-py3-none-any.whl.metadata (12 kB)
  Using cached imbalanced_learn-0.8.0-py3-none-any.whl.metadata (11 kB)
  Using cached imbalanced_learn-0.7.0-py3-none-any.whl.metadata (11 kB)
  Using cached imbalanced_learn-0.6.2-py3-none-any.whl.metadata (11 kB)
  Using cached imbalanced_learn-0.6.1-py3-none-any.whl.metadata (11 kB)
  Using cached imbalanced_learn-0.6.0-py3-none-any.whl.metadata (11 kB)
  Using cached imbalanced_learn-0.5.0-py3-none-any.whl.metadata (10 kB)
  Using cached imbalanced_learn-0.4.3-py3-none-any.whl.metadata (10 kB)
  Using cached imbalanced_learn-0.4.2-py3-none-any.whl.metadata (10 kB)
  Using cached imbalanced_learn-0.4.1-py3-none-any.whl.metadata (10 kB)
  Using cached imbalanced_learn-0.4.0-py3-none-any.whl.metadata (12 kB)
  Using cached imbalanced_learn-0.3.3-py3-none-any.whl.metadata (9.8 kB)
  Using cached imbalanced_learn-0.3.2-py3-none-any.whl.metadata (9.8 kB)
  Using cached imbalanced_learn-0.3.1-py3-none-any.whl.metadata (9.8 kB)
  Using cached imbalanced_learn-0.3.0-py3-none-any.whl.metadata (9.9 kB)
```

It finally terminates with:

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
```

See:
https://github.com/aeon-toolkit/aeon/actions/runs/12390736933/job/34586409381

And:
https://github.com/aeon-toolkit/aeon/actions/runs/12391232200/job/34587902633

### Steps/Code to reproduce the bug

Run CI

### Expected results

CI should not take >30 minutes and terminate.

### Actual results

Should run just fine

### Versions

windows/python 3.9 and ubuntu/python 3.9

**Comment by patrickzib** [comment]
Matplotlib dropped python 3.9 support from version 3.10:

https://github.com/matplotlib/matplotlib/blob/main/doc/devel/min_dep_policy.rst

**Comment by MatthewMiddlehurst** [comment]
Fixed with comment in pyproject file.
