### ISSUE TITLE
[BUG] Packaging should be included as a soft dependency

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#256]
When installing `aeon` with `pip`, i try to do the following:

`from aeon.transformations.panel.dictionary_based import SAX`

but i get the following error

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aeon.transformations.panel.dictionary_based'`

**Comment by MatthewMiddlehurst** [comment]
The current default release is identical to `sktime v0.16.0` apart from a couple of bits outside the package proper. You will have to import `from sktime` or install the pre-release.

**Comment by hadifawaz1999** [comment]
I tried to use `from sktime` to import the same thing but got the following:

`ModuleNotFoundError: No module named 'packaging'`

**Comment by hadifawaz1999** [comment]
here is the full error output @MatthewMiddlehurst 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/transformations/panel/dictionary_based/__init__.py", line 5, in <module>
    from sktime.transformations.panel.dictionary_based._paa import PAA
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/transformations/panel/dictionary_based/_paa.py", line 5, in <module>
    from sktime.datatypes._panel._convert import from_nested_to_2d_array
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/__init__.py", line 6, in <module>
    from sktime.datatypes._check import (
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/_check.py", line 32, in <module>
    from sktime.datatypes._hierarchical import check_dict_Hierarchical
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/_hierarchical/__init__.py", line 4, in <module>
    from sktime.datatypes._hierarchical._check import check_dict as check_dict_Hierarchical
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/_hierarchical/_check.py", line 47, in <module>
    from sktime.datatypes._panel._check import check_pdmultiindex_panel
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/_panel/__init__.py", line 4, in <module>
    from sktime.datatypes._panel._check import check_dict as check_dict_Panel
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/_panel/_check.py", line 46, in <module>
    from sktime.datatypes._series._check import (
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/_series/__init__.py", line 4, in <module>
    from sktime.datatypes._series._check import check_dict as check_dict_Series
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/datatypes/_series/_check.py", line 43, in <module>
    from sktime.utils.validation._dependencies import _check_soft_dependencies
  File "/home/aismailfawaz/phd/open_source/for_aeon/SAX_flexibility/aeon-test-release/lib/python3.8/site-packages/sktime/utils/validation/_dependencies.py", line 12, in <module>
    from packaging.requirements import InvalidRequirement, Requirement
ModuleNotFoundError: No module named 'packaging'

```

**Comment by MatthewMiddlehurst** [comment]
hmm maybe best to just add it as a dependency. others have reported this. just `pip install packaging` for now.

**Comment by TonyBagnall** [comment]
packaging should be a hard dependency, see https://github.com/aeon-toolkit/aeon/issues/55
