### ISSUE TITLE
[BUG] ElasticEnsemble does not support `euclidean` or `twe` distance functions

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#725]
### Describe the bug

Identified whilst writing coverage tests: EE does not work with all distances in the distance module, including euclidean. If you use it with defaults it crashes without informative exception. With this

```python 
ee = ElasticEnsemble(distance_measures=["euclidean"],
                     proportion_train_in_param_finding=0.4)
```
it raises TypeError: Parameter grid should be a dict or a list, got: None of type NoneType

### Steps/Code to reproduce the bug

```python
from aeon.classification.distance_based import ElasticEnsemble
from aeon.utils._testing.collection import make_2d_test_data
X, y = make_2d_test_data(n_cases=10, n_timepoints=10, n_labels=2)
ee = ElasticEnsemble(distance_measures=["euclidean"])
ee.fit(X,y)
```   

### Expected results

works

### Actual results

```python-traceback
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.11.0
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
runfile('C:\\Code\\aeon\\aeon\\local\\debug.py', wdir='C:\\Code\\aeon\\aeon\\local')
Traceback (most recent call last):
  File "C:\Code\aeon\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c35d1f6140d9>", line 1, in <module>
    runfile('C:\\Code\\aeon\\aeon\\local\\debug.py', wdir='C:\\Code\\aeon\\aeon\\local')
  File "C:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Code\aeon\aeon\local\debug.py", line 5, in <module>
    ee.fit(X,y)
  File "C:\Code\aeon\aeon\classification\base.py", line 186, in fit
    self._fit(X, y)
  File "C:\Code\aeon\aeon\classification\distance_based\_elastic_ensemble.py", line 271, in _fit
    grid.fit(param_train_to_use, param_train_y)
  File "C:\Code\aeon\venv\lib\site-packages\sklearn\model_selection\_search.py", line 874, in fit
    self._run_search(evaluate_candidates)
  File "C:\Code\aeon\venv\lib\site-packages\sklearn\model_selection\_search.py", line 1388, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Code\aeon\venv\lib\site-packages\sklearn\model_selection\_search.py", line 94, in __init__
    raise TypeError(
TypeError: Parameter grid should be a dict or a list, got: None of type NoneType
```

### Versions

<details>
System:
    python: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
executable: C:\Code\aeon\venv\Scripts\python.exe
   machine: Windows-10-10.0.22621-SP0
Python dependencies:
          pip: 23.0.1
   setuptools: 67.3.2
 scikit-learn: 1.2.2
         aeon: 0.3.0
  statsmodels: 0.13.5
        numpy: 1.23.5
        scipy: 1.10.1
       pandas: 2.0.3
   matplotlib: 3.7.1
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: 2.0.3
      tsfresh: 0.20.0
</details>

**Comment by itsdivya1309** [comment]
Can I work on this issue?
