### ISSUE TITLE
[BUG] CBOSS crashes with small train set siz

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#726]
### Describe the bug

found when writing tests for HC1, CBOSS crashes with train always with trains set 4, often set size of 10, not with train size 15

### Steps/Code to reproduce the bug

```python
    from aeon.classification.dictionary_based import ContractableBOSS
    from aeon.utils._testing.collection import make_2d_test_data
    X, y = make_2d_test_data(n_cases=4, n_timepoints=100, n_labels=2)
    cboss = ContractableBOSS()
    cboss.fit(X, y)
```

### Expected results

either informative exception about train set size or should work.

 

### Actual results

```python-traceback
Traceback (most recent call last):
  File "C:\Code\aeon\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c35d1f6140d9>", line 1, in <module>
    runfile('C:\\Code\\aeon\\aeon\\local\\debug.py', wdir='C:\\Code\\aeon\\aeon\\local')
  File "C:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Code\aeon\aeon\local\debug.py", line 6, in <module>
    cboss.fit(X, y)
  File "C:\Code\aeon\aeon\classification\base.py", line 186, in fit
    self._fit(X, y)
  File "C:\Code\aeon\aeon\classification\dictionary_based\_cboss.py", line 266, in _fit
    boss._clean()
  File "C:\Code\aeon\aeon\classification\dictionary_based\_boss.py", line 691, in _clean
    self._transformer.words = None
AttributeError: 'NoneType' object has no attribute 'words'
```

**Comment by hedeershowk** [comment]
@MatthewMiddlehurst reading through the code this seems like a simple fix if you want to just guard against a `None` transformer in the `_clean()` function in `IndividualBOSS`.  But...seems to me like there's no reason not to initialize the transformer in the init of `IndividualBoss`.  I'm going to open a PR for the latter solution and tag you in it too.

**Comment by TonyBagnall** [comment]
```python 
from aeon.classification.dictionary_based import ContractableBOSS
from aeon.testing.utils.data_gen import make_2d_test_data
X, y = make_2d_test_data(n_cases=4, n_timepoints=100, n_labels=2)
cboss = ContractableBOSS()
cboss.fit(X, y)
```
now works, fixed by #741
