### ISSUE TITLE
[BUG] problem with matplotlib and pycharm on windows when drawing CD

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#755]
### Describe the bug

I think this came in with the new matplotlib, had a look but I'm not sure how to fix it

https://github.com/matplotlib/matplotlib/issues/23911

### Steps/Code to reproduce the bug

```python
from aeon.benchmarking import plot_critical_difference
from aeon.datasets.dataset_collections import univariate
from aeon.benchmarking.results_loaders import (
    get_estimator_results,
    get_estimator_results_as_array,
)

classifiers = [
    "FreshPRINCEClassifier",
    "HIVECOTEV2",
    "InceptionTimeClassifier",
    "WEASEL2"

]
datasets = univariate
# get results. To read locally, set the path variable.
# If you do not set path, results are loaded from
# https://timeseriesclassification.com/results/ReferenceResults.
# You can download the files directly from there
default_split_all, data_names = get_estimator_results_as_array(
    estimators=classifiers)
print(" Shape of results = ",default_split_all.shape)
plot_critical_difference(default_split_all, classifiers)
```

### Expected results

draws a CD

### Actual results

```python-traceback
 File "C:\Code\aeon\aeon\local\debug.py", line 23, in <module>
    plot_critical_difference(default_split_all, classifiers)
  File "C:\Code\aeon\aeon\benchmarking\_critical_difference.py", line 305, in plot_critical_difference
    fig = plt.figure(figsize=(width, height))
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 934, in figure
    manager = new_figure_manager(
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 464, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 441, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 280, in _get_backend_mod
    switch_backend(rcParams._get("backend"))  # type: ignore[attr-defined]
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'

```

### Versions

<details>

Python dependencies:
          pip: 23.0
   setuptools: 67.2.0
 scikit-learn: 1.2.2
         aeon: 0.4.0
  statsmodels: 0.14.0
        numpy: 1.24.3
        scipy: 1.11.2
       pandas: 2.0.3
   matplotlib: 3.8.0
       joblib: 1.3.2
        numba: 0.57.1
     pmdarima: 2.0.3
      tsfresh: 0.20.1
</details>

**Comment by TonyBagnall** [comment]
plots with matplotlib version 3.5. Gives the above error with 3.6, 3.8. 3.7 gives this error

```python-traceback
Traceback (most recent call last):
  File "C:\Code\aeon\aeon\local\debug.py", line 24, in <module>
    plot_critical_difference(default_split_all, classifiers)
  File "C:\Code\aeon\aeon\benchmarking\_critical_difference.py", line 305, in plot_critical_difference
    fig = plt.figure(figsize=(width, height))
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 813, in figure
    manager = new_figure_manager(
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 382, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 360, in _warn_if_gui_out_of_main_thread
    if _get_required_interactive_framework(_get_backend_mod()):
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 208, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
  File "C:\Code\aeon\venv\lib\site-packages\matplotlib\pyplot.py", line 331, in switch_backend
    manager_pyplot_show = vars(manager_class).get("pyplot_show")
TypeError: vars() argument must have __dict__ attribute
```

**Comment by TonyBagnall** [comment]
fixed by https://github.com/aeon-toolkit/aeon/pull/719 although Im getting a different error from matplotlib 3.8, its something pycharm related, passes all CI
