### ISSUE TITLE
[BUG] _load_data expects a metadata key timestamps 

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#905]
### Describe the bug

since the introduction of the ability to load timestamped data in #887 the function aeon.datasets._data_loaders._load_data expects the metadata key "timestamps". However, it was always meant to be optional: no need to have the flag in the metadata if the series dont have timestamps.  All the UCR data do have this flag, but this has lead to an overnight fail on test__load_data, which creates an example without the timestamps key in the metadata

### Steps/Code to reproduce the bug

```
from aeon.datasets.tests.test_data_loaders import test__load_data

test__load_data()
```

### Expected results

pass test

### Actual results

```python-traceback
Traceback (most recent call last):
  File "C:\Code\aeon\aeon\local\debug.py", line 3, in <module>
    test__load_data()
  File "C:\Code\aeon\aeon\datasets\tests\test_data_loaders.py", line 249, in test__load_data
    X, y, meta_data = _load_data(file, meta_data)
  File "C:\Code\aeon\aeon\datasets\_data_loaders.py", line 157, in _load_data
    if meta_data["timestamps"]:
KeyError: 'timestamps'

Process finished with exit code 1
```

**Comment by TonyBagnall** [comment]
in fact its only an issue if you use the protected function _load_data function directly, because if you _load_header first it defaults timestamps to false
