### ISSUE TITLE
[ENH] Remove tensorflow-probability requirement for deep learners

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#922]
### Describe the feature or idea you want to propose

Currently, you cannot use any deep learners without installing tensorflow-probability. This is not used in the deep learners and so should not be part of the soft dependency. Thought I had raised this before but cant find an issue, will merge if Im wrong

### Describe your proposed solution

separate the checks for tensorflow and tensorflow-probability. I'm not sure why there are separate functions for _check_soft_dependencies and _check_dl_dependencies in the first place

### Describe alternatives you've considered, if relevant

remove the tensorflow-probability dependency. Its only use is in base forecaster for a normal distribution. This whole function looks a bit of a mess to me (soft dep is checked in predict_proba)

```python
        import tensorflow_probability as tfp
       d = tfp.distributions.Normal
        pred_dist = d(loc=pred_mean, scale=pred_std)
```
```python

    # todo: does not work properly for multivariate or hierarchical
    #   still need to implement this - once interface is consolidated
    def _predict_proba(self, fh, X, marginal=True):
        """Compute/return fully probabilistic forecasts.

        private _predict_proba containing the core logic, called from predict_proba

        Parameters
        ----------
        fh : guaranteed to be ForecastingHorizon
            The forecasting horizon with the steps ahead to to predict.
        X : optional (default=None)
            guaranteed to be of a type in self.get_tag("X_inner_type")
            Exogeneous time series to predict from.
        marginal : bool, optional (default=True)
            whether returned distribution is marginal by time index

        Returns
        -------
        pred_dist : tfp Distribution object
            if marginal=True:
                batch shape is 1D and same length as fh
                event shape is 1D, with length equal number of variables being forecast
                i-th (batch) distribution is forecast for i-th entry of fh
                j-th (event) index is j-th variable, order as y in `fit`/`update`
            if marginal=False:
                there is a single batch
                event shape is 2D, of shape (len(fh), no. variables)
                i-th (event dim 1) distribution is forecast for i-th entry of fh
                j-th (event dim 1) index is j-th variable, order as y in `fit`/`update`
        """
        import tensorflow_probability as tfp

        # default behaviour is implemented if one of the following three is implemented
        implements_interval = self._has_implementation_of("_predict_interval")
        implements_quantiles = self._has_implementation_of("_predict_quantiles")
        implements_var = self._has_implementation_of("_predict_var")
        can_do_proba = implements_interval or implements_quantiles or implements_var

        if not can_do_proba:
            raise RuntimeError(
                f"{self.__class__.__name__} does not implement "
                "probabilistic forecasting, "
                'but "capability:pred_int" flag has been set to True incorrectly. '
                "This is likely a bug, please report, and/or set the flag to False."
            )

        # if any of the above are implemented, predict_var will have a default
        #   we use predict_var to get scale, and predict to get location
        pred_var = self._predict_var(fh=fh, X=X)
        pred_std = np.sqrt(pred_var)
        pred_mean = self.predict(fh=fh, X=X)
        # ensure that pred_mean is a pd.DataFrame
        df_types = ["pd.DataFrame", "pd-multiindex", "pd_multiindex_hier"]
        pred_mean = convert_to(pred_mean, to_type=df_types)
        # pred_mean and pred_var now have the same format

        d = tfp.distributions.Normal
        pred_dist = d(loc=pred_mean, scale=pred_std)

        return pred_dist
```

**Comment by TonyBagnall** [comment]
so if you do this
```python
from aeon.forecasting.theta import ThetaForecaster
from aeon.datasets import load_airline
y = load_airline()
exp = ThetaForecaster()
exp.fit(y, fh=1)
print(exp.predict())
print(exp.predict_proba())
```
without tensorflow-probability installed, you get this

```python-traceback
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.11.0
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
runfile('C:\\Code\\aeon\\aeon\\local\\debug.py', wdir='C:\\Code\\aeon\\aeon\\local')
1961-01    434.657183
Freq: M, Name: Number of airline passengers, dtype: float64
Traceback (most recent call last):
  File "C:\Code\aeon\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c35d1f6140d9>", line 1, in <module>
    runfile('C:\\Code\\aeon\\aeon\\local\\debug.py', wdir='C:\\Code\\aeon\\aeon\\local')
  File "C:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Code\aeon\aeon\local\debug.py", line 18, in <module>
    print(exp.predict_proba())
  File "C:\Code\aeon\aeon\forecasting\base\_base.py", line 782, in predict_proba
    pred_dist = self._predict_proba(fh=fh, X=X_inner, marginal=marginal)
  File "C:\Code\aeon\aeon\forecasting\base\_base.py", line 2225, in _predict_proba
    d = tfp.distributions.Normal
AttributeError: module 'tensorflow_probability' has no attribute 'distributions'
```
which is a very confusing error. There must be a way of modelling a normal distribution in statsmodels?

**Comment by TonyBagnall** [comment]
could do this instead?
```python
import scipy.stats as stats

# Example mean and standard deviation
pred_mean = 0
pred_std = 1

# Creating a normal distribution instance
pred_dist = stats.norm(loc=pred_mean, scale=pred_std)

# Now you can use pred_dist to compute probabilities, generate samples, etc.
# For example, generating random samples:
samples = pred_dist.rvs(size=1000)
```
